# Generated by Django 3.2.25 on 2026-04-23 11:28

from django.db import migrations, models
import django.db.models.deletion
import django.db.models.expressions
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AllDistricts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('name_bn', models.CharField(blank=True, max_length=50, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'all_districts',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AllDivisions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('name_bn', models.CharField(blank=True, max_length=50, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'all_divisions',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AllThanas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('name_bn', models.CharField(blank=True, max_length=50, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'all_thanas',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AllUpazilas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('name_bn', models.CharField(blank=True, max_length=50, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'all_upazilas',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Districts',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('division', models.CharField(max_length=255)),
                ('district', models.CharField(max_length=255)),
                ('thana', models.CharField(max_length=255)),
                ('postoffice', models.CharField(max_length=255)),
                ('postcode', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField()),
                ('updated_at', models.DateTimeField()),
            ],
            options={
                'db_table': 'districts',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Chamber',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.IntegerField(blank=True, null=True)),
                ('updated_by', models.IntegerField(blank=True, null=True)),
                ('deleted_by', models.IntegerField(blank=True, null=True)),
                ('name', models.CharField(max_length=150)),
                ('address', models.CharField(max_length=255)),
                ('state', models.CharField(blank=True, db_index=True, max_length=100, null=True)),
                ('city', models.CharField(blank=True, db_index=True, max_length=100, null=True)),
                ('upazila', models.CharField(blank=True, db_index=True, max_length=120, null=True)),
                ('zip_code', models.CharField(blank=True, db_index=True, max_length=20, null=True)),
                ('phone', models.CharField(blank=True, max_length=20, null=True)),
                ('timezone', models.CharField(default='UTC', max_length=64)),
                ('is_active', models.BooleanField(default=True)),
                ('latitude', models.FloatField(blank=True, null=True)),
                ('longitude', models.FloatField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ChamberSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.IntegerField(blank=True, null=True)),
                ('updated_by', models.IntegerField(blank=True, null=True)),
                ('deleted_by', models.IntegerField(blank=True, null=True)),
                ('day_of_week', models.SmallIntegerField()),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('effective_start_date', models.DateField(blank=True, null=True)),
                ('effective_end_date', models.DateField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='District',
            fields=[
                ('district_id', models.IntegerField(db_column='DistrictId', primary_key=True, serialize=False)),
                ('district_name', models.CharField(blank=True, db_column='DistrictName', max_length=1000, null=True)),
                ('district_bng_name', models.CharField(blank=True, db_column='DistrictBngName', max_length=200, null=True)),
                ('latitude', models.FloatField(blank=True, db_column='Latitude', null=True)),
                ('longitude', models.FloatField(blank=True, db_column='Longitude', null=True)),
                ('web_url', models.CharField(blank=True, db_column='WebUrl', max_length=1000, null=True)),
            ],
            options={
                'db_table': 'District',
            },
        ),
        migrations.CreateModel(
            name='Division',
            fields=[
                ('division_id', models.IntegerField(db_column='DivisionId', primary_key=True, serialize=False)),
                ('division_name', models.CharField(db_column='DivisionName', max_length=100)),
                ('division_bng_name', models.CharField(blank=True, db_column='DivisionBngName', max_length=200, null=True)),
                ('division_url', models.CharField(blank=True, db_column='DivisionUrl', max_length=50, null=True)),
            ],
            options={
                'db_table': 'Division',
            },
        ),
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.IntegerField(blank=True, null=True)),
                ('updated_by', models.IntegerField(blank=True, null=True)),
                ('deleted_by', models.IntegerField(blank=True, null=True)),
                ('full_name', models.CharField(max_length=150)),
                ('full_name_ci', models.CharField(db_index=True, max_length=150)),
                ('gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female'), ('Other', 'Other')], default='Other', max_length=10)),
                ('phone', models.CharField(blank=True, max_length=20, null=True)),
                ('email', models.CharField(blank=True, max_length=150, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Hospital',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.IntegerField(blank=True, null=True)),
                ('updated_by', models.IntegerField(blank=True, null=True)),
                ('deleted_by', models.IntegerField(blank=True, null=True)),
                ('name', models.CharField(max_length=200)),
                ('legal_name', models.CharField(blank=True, max_length=200, null=True)),
                ('phone', models.CharField(blank=True, max_length=20, null=True)),
                ('website', models.CharField(blank=True, max_length=255, null=True)),
                ('state', models.CharField(blank=True, db_index=True, max_length=100, null=True)),
                ('city', models.CharField(blank=True, db_index=True, max_length=100, null=True)),
                ('zip_code', models.CharField(blank=True, db_index=True, max_length=20, null=True)),
                ('address', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Specialization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.IntegerField(blank=True, null=True)),
                ('updated_by', models.IntegerField(blank=True, null=True)),
                ('deleted_by', models.IntegerField(blank=True, null=True)),
                ('name', models.CharField(max_length=150, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='DoctorSearchIndex',
            fields=[
                ('doctor', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='search_index', serialize=False, to='directory.doctor')),
                ('search_text', models.TextField()),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Upazilas',
            fields=[
                ('upazilas_id', models.IntegerField(db_column='UpazilasId', primary_key=True, serialize=False)),
                ('upazilas_name', models.CharField(db_column='UpazilasName', max_length=25)),
                ('upazilas_bng_name', models.CharField(db_column='UpazilasBngName', max_length=250)),
                ('web_url', models.CharField(db_column='WebUrl', max_length=50)),
                ('district', models.ForeignKey(db_column='DistrictId', on_delete=django.db.models.deletion.DO_NOTHING, related_name='upazilas', to='directory.district')),
            ],
            options={
                'db_table': 'Upazilas',
            },
        ),
        migrations.CreateModel(
            name='Union',
            fields=[
                ('union_id', models.IntegerField(db_column='UnionId', primary_key=True, serialize=False)),
                ('union_name', models.CharField(db_column='UnionName', max_length=25)),
                ('union_bng_name', models.CharField(db_column='UnionBngName', max_length=250)),
                ('web_url', models.CharField(db_column='WebUrl', max_length=50)),
                ('upazila', models.ForeignKey(db_column='UpazilaId', on_delete=django.db.models.deletion.DO_NOTHING, related_name='unions', to='directory.upazilas')),
            ],
            options={
                'db_table': 'Union',
            },
        ),
        migrations.AddIndex(
            model_name='specialization',
            index=models.Index(fields=['name'], name='directory_s_name_b19d98_idx'),
        ),
        migrations.AddIndex(
            model_name='hospital',
            index=models.Index(fields=['state', 'city', 'zip_code'], name='directory_h_state_4b90ba_idx'),
        ),
        migrations.AddIndex(
            model_name='hospital',
            index=models.Index(fields=['name'], name='directory_h_name_28722a_idx'),
        ),
        migrations.AddField(
            model_name='doctor',
            name='specializations',
            field=models.ManyToManyField(blank=True, related_name='doctors', to='directory.Specialization'),
        ),
        migrations.AddField(
            model_name='district',
            name='division',
            field=models.ForeignKey(db_column='DivisionId', on_delete=django.db.models.deletion.DO_NOTHING, related_name='districts', to='directory.division'),
        ),
        migrations.AddField(
            model_name='chamberschedule',
            name='chamber',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedules', to='directory.chamber'),
        ),
        migrations.AddField(
            model_name='chamber',
            name='doctor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chambers', to='directory.doctor'),
        ),
        migrations.AddField(
            model_name='chamber',
            name='hospital',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='chambers', to='directory.hospital'),
        ),
        migrations.AddIndex(
            model_name='doctorsearchindex',
            index=models.Index(fields=['doctor'], name='directory_d_doctor__459f1f_idx'),
        ),
        migrations.AddIndex(
            model_name='doctor',
            index=models.Index(fields=['full_name'], name='directory_d_full_na_5e090a_idx'),
        ),
        migrations.AddIndex(
            model_name='doctor',
            index=models.Index(fields=['full_name_ci'], name='directory_d_full_na_fbb813_idx'),
        ),
        migrations.AddIndex(
            model_name='chamberschedule',
            index=models.Index(fields=['day_of_week', 'start_time', 'end_time'], name='directory_c_day_of__f01e3e_idx'),
        ),
        migrations.AddConstraint(
            model_name='chamberschedule',
            constraint=models.CheckConstraint(check=models.Q(('day_of_week__gte', 0), ('day_of_week__lte', 6)), name='ck_schedule_day_range'),
        ),
        migrations.AddConstraint(
            model_name='chamberschedule',
            constraint=models.CheckConstraint(check=models.Q(('start_time__lt', django.db.models.expressions.F('end_time'))), name='ck_schedule_start_before_end'),
        ),
        migrations.AddConstraint(
            model_name='chamberschedule',
            constraint=models.UniqueConstraint(fields=('chamber', 'day_of_week', 'start_time', 'end_time'), name='uq_schedule_exact_window'),
        ),
        migrations.AddIndex(
            model_name='chamber',
            index=models.Index(fields=['state', 'city', 'zip_code', 'upazila'], name='directory_c_state_06be72_idx'),
        ),
        migrations.AddConstraint(
            model_name='chamber',
            constraint=models.UniqueConstraint(fields=('doctor', 'name', 'address'), name='uq_chamber_doctor_name_address'),
        ),
    ]
